package com.innercircle.sacco.ledger.entity;

public enum TransactionType {
    CONTRIBUTION,
    LOAN_DISBURSEMENT,
    LOAN_REPAYMENT,
    PAYOUT,
    PENALTY,
    INTEREST_ACCRUAL,
    MANUAL_ADJUSTMENT,
    LOAN_REVERSAL,
    CONTRIBUTION_REVERSAL,
    PENALTY_WAIVER,
    BENEFIT_DISTRIBUTION
}
